### ISSUE TITLE
Crashing when pattern is incorrect in ref(erenced) schema

### ISSUE THREAD

**Issue by vespakoen** [playlyfe/themis#3]
Hey!

Thanks for the library, looks pretty sweet.
Unfortunately, it with the following error.

```
undefined:65
   message: _stringify(data) + " should match the pattern " + _schema.pattern,
                                                                     ^
TypeError: Cannot read property 'pattern' of undefined
    at Object.validators.types#/definitions/uuid (eval at <anonymous> (/home/koen/Projects/trapps/code/node-projector/node_modules/themis/src/themis.js:2608:10), <anonymous>:65:87)
    at Object.validators.kitchensink#/properties/id (eval at <anonymous> (/home/koen/Projects/trapps/code/node-projector/node_modules/themis/src/themis.js:2608:10), <anonymous>:131:53)
    at Object.validators.kitchensink (eval at <anonymous> (/home/koen/Projects/trapps/code/node-projector/node_modules/themis/src/themis.js:2608:10), <anonymous>:115:70)
    at eval (eval at <anonymous> (/home/koen/Projects/trapps/code/node-projector/node_modules/themis/src/themis.js:2608:10), <anonymous>:134:37)
    at /home/koen/Projects/trapps/code/node-projector/node_modules/themis/src/themis.js:2631:22
    at Object.<anonymous> (/home/koen/Projects/trapps/code/node-projector/test.js:43:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
```

Here is the (stripped down) schema

```json
[
  {
    "id": "types",
    "$schema": "http://json-schema.org/draft-04/schema#",
    "definitions": {
      "uuid": {
        "type": "string",
        "pattern": "^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$"
      }
    }
  },
  {
    "id": "kitchensink",
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "properties": {
      "id": { "$ref": "types#/definitions/uuid" }
    }
  }
]
```

And this is my test code:

```js
var validator = Themis.validator(schemas);

var item = {
  "id": "incorrect value"
};

var report = validator(item, 'kitchensink');

console.log(report);
```

Maybe I am doing it wrong?

I would have wished to figure it out / send a patch, but coding at this meta level currently makes my mind explode ;)

Thanks!

**Comment by pyros2097** [comment]
I Think you should first register the format like this,
```javascript
Themis.registerFormat('uuidv1', function(str) {  
       return /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/.test(str) 
}
```
Then in your schema do this,
```json
 "uuid": {
        "type": "string",
        "format": "uuidv1"
      }
```

**Comment by kumarharsh** [comment]
@pyros2097 It's not about registering the new format. What @vespakoen is saying is that Themis is not able to resolve the `ref` to fragments within references, like the `#/definitions/uuid` path within the schema with the ID `types`.

**Comment by vespakoen** [comment]
Here is the complete code to test it out:

```js

var schemas = [
  {
    "id": "types",
    "$schema": "http://json-schema.org/draft-04/schema#",
    "definitions": {
      "uuid": {
        "type": "string",
        "pattern": "^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$"
      }
    }
  },
  {
    "id": "kitchensink",
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "properties": {
      "id": { "$ref": "types#/definitions/uuid" }
    }
  }
];

var validator = Themis.validator(schemas);

var item = {
  "id": "incorrect value"
};

var report = validator(item, 'kitchensink');
console.log(report);
```

Also check out my updated error message in the issue report.
